---
title: "Testing RSR"
author: "Ellen Graham"
date: "9/8/2020"
output: html_document
---

```{r}
library(dplyr)
library(ggplot2)
library(here)
library(ngspatial)
library(MASS)
library(broom)
library(spaMM)
library(fields)
library(Rcpp)

sourceCpp(here("Code", "RSRcode", "phiCfast.cpp"))

source(here("Code", "RSRcode", "spatialPoisson.R"))


data(infant)
```


```{r}


infant_small <- infant[1:500,]

infant_small$low_weight = infant_small$low_weight / infant_small$births
Z = infant_small$deaths
X = cbind(1, infant_small$low_weight, infant_small$black, infant_small$hispanic, infant_small$gini, infant_small$affluence, infant_small$stability)
data(A)

A_small <- A[1:500, 1:500]

```

takes 23 minutes to run be careful

```{r}


set.seed(123456)
fit = sparse.sglmm(Z ~ X - 1 + offset(log(infant_small$births)), family = poisson, A = A_small, method = "RSR",
                   tune = list(sigma.s = 0.02), verbose = TRUE)
summary(fit)


fit_lm <- glm(Z ~ X - 1 + offset(log(infant_small$births)), family = poisson)
summary(fit_lm)
confint(fit_lm)

fit_sparse.sglmm <- fit
# these are completley different results from what the Khan paper says we should see!?!?!
```






## Attempting to simulate the data from Guan and Haran 2018


### Simulate data
```{r}

n <- 100

set.seed(454)

x1 <- runif(n)
x2 <- runif(n)

nu <- 2.5
sigma2 <- 1
phi <- 0.2

tau2 <- 0.1

h <- as.matrix(dist(data.frame(x1 = x1, x2 = x2)))

matern_covariance <- sigma2 * (1 + sqrt(5)*h/phi + 5*h^2 / (3*phi^2)) * exp(-1*sqrt(5)*h/phi)

matern_covariance2 <- fields::Matern(h, range = phi/sqrt(2*nu), phi = sigma2, smoothness = nu)

W <- mvrnorm(mu = rep(0, n), Sigma = matern_covariance)

epsilon <- rnorm(n, 0, sqrt(tau2))

y <- x1 + x2 + W + epsilon

sim_data <- tibble(x1 = x1, x2 = x2, W = W, epsilon = epsilon, y = y)
```


```{r}
sim_data %>% 
  ggplot() +
  geom_point(aes(x = x1, y = x2, color = y)) +
  scale_color_viridis_c()

```

### Begin Fitting Models

```{r}
linear_model <- lm(y ~ x1 + x2, data = sim_data)
linear_model %>% 
  tidy(conf.int = TRUE)
```

```{r}
sglmm <- fitme(y ~ x1 + x2 + Matern(1|x1 + x2), data = sim_data)
summary(sglmm)

# again just completley wrong
```

```{r}
design_matrix <- model.matrix(~ x1 + x2,
                              data = sim_data)

covfn <- covfndef(nu)
adapt <- c("batchlength"=1e4,"n.batch"=100) # set Monte Carlo sample size = batchlength*n.batch

starting <- list("beta"=coef(linear_model),"s2"=2,"phi"=0.5) # set starting values

tuning   <- list("beta"=c(sqrt(diag(vcov(linear_model)))),"s2"=0.1,"phi"=0.01,"w"=0.1) # set tuning parameters

priors   <- list("beta.normal"=c(100),"s2.IG"=c(2,2),"phi.Unif"=c(0.01, 1.5)) # set priors

core = 1
mul = 2
rank = 50
```

```{r}
source(here("Code", "RSRcode", "spatialPoisson.R"))

rsr_fit <- poi_gp_arrpfit(O = y, 
               X = design_matrix,
               coords = cbind(x1, x2), 
               covfn = covfn,
               adapt = adapt,
               nu = nu,
               starting = starting,
               tuning = tuning,
               priors = priors,
               core = core,
               mul = mul,
               rank = rank)

```

