---
title: "Test Models"
output: html_document
---

```{r}
library(MASS)
```


First Model
```{r}
y = c(0,1,2,3,2,1) # space then time
locations <-  matrix(c(1,1,
                     2,1,
                     0,3), ncol = 2, byrow = TRUE)
time <- c(1,2)



d = as.matrix(dist(locations))

h = as.matrix(dist(time))

```

spatial covariance matrix for Matern(nu = 2.5, phi = 1), sigma2 = 1
```{r}
phi = 2
V = 1 # temporal scaling parameter

space_cov <- (1 + sqrt(5)*d/phi + 5*d^2 / (3*phi^2)) * exp(-1*sqrt(5)*d/phi)

time_cov <- exp(-h/3)
```


Lets just simulate the data and see what happens to the covariance matrix. 

```{r}
time_svd <- svd(time_cov)
space_svd <- svd(space_cov)

time_u <- time_svd$u
space_u <- space_svd$u
time_d <- diag(time_svd$d)
space_d <- diag(space_svd$d)
```


Take draws from random effects
```{r}

y_draws <- matrix(nrow = 10000, ncol = 6)

for(i in 1: 10000) {
  delta <- rnorm(3, sd = 1)
  alpha <- rnorm(2, sd = 1) 

  epsilon <- rnorm(6, sd = 0.05)

  y <- rep(space_u %*% space_d ^ (1/2) %*% delta, 2) +
    rep(time_u %*% time_d ^ (1/2) %*% alpha, each = 3)
  
  y_draws[i, ] <- y
}

temp <- cov(y_draws, y_draws)
  

temp
space_cov
time_cov
```


```{r}
mvrnorm(n = 6, sigma = 0.2, )
```

