# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiply a number by two
#'
#' @param x A single integer.
#' @export
rp <- function(phi_r, coords, n_r, r_r, nu_r, num_r) {
    .Call('_rsrHonors_rp', PACKAGE = 'rsrHonors', phi_r, coords, n_r, r_r, nu_r, num_r)
}

#' Matrix Multiplication
#'
#' @param x A single integer.
#' @export
mmC <- function(A, B, n, b, num) {
    .Call('_rsrHonors_mmC', PACKAGE = 'rsrHonors', A, B, n, b, num)
}

